#ifndef __exit_codes_hpp_included
#define __exit_codes_hpp_included

#define CANNOT_WRITE_DISTANCE_MATRIX 18
#define INSUFFICIENT_MEMORY_FOR_MEDOID_CALC 19
#define MEMORY_MAPPING_FILE_OPEN_FAILED 20
#define MEMORY_MAPPING_FAILED 21
#define CANNOT_WRITE_DTW_PATH 22
#define CANNOT_WRITE_DBA_AVG 23
#define CANNOT_READ_SEQUENCE_PREFIX_FILE 24
#define CANNOT_COPY_PREFIX_CHOPPED_SEQ 25
#define CANNOT_WRITE_DTW_PATH_MATRIX 26
#define INSUFFICIENT_L1CACHE_FOR_EXPECTED_SEGMENT_SIZE 27 
#define FAST5_FILE_UNREADABLE 28
#define FAST5_FILE_CONTENTS_UNRECOGNIZED 29
#define FAST5_CANNOT_MALLOC_READNAME 30
#define FAST5_HDF5_API_ERROR 31
#define NOT_ENOUGH_SEQUENCES 32
#define CANNOT_WRITE_MEMBERSHIP 33
#define CANNOT_ALLOCATE_PAIRWISE_DIST_ARRAY 34
#define MEMCPY_FAILURE 35
#define MEDOID_FINDING_ERROR 36
#define CANNOT_WRITE_UPDATED_FAST5 37
#define CANNOT_ALLOCATE_HOST_STRIPED_STEP_MATRIX 38
#define CANNOT_ALLOCATE_HOST_FULL_STEP_MATRIX 39
#define CANNOT_WRITE_UPDATED_SLOW5 40
#define SLOW5_FILE_UNREADABLE 41
#endif
