#ifndef __exit_codes_hpp_included
#define __exit_codes_hpp_included

#define CANNOT_WRITE_DISTANCE_MATRIX 18
#define INSUFFICIENT_MEMORY_FOR_MEDOID_CALC 19
#define MEMORY_MAPPING_FILE_OPEN_FAILED 20
#define MEMORY_MAPPING_FAILED 21
#define CANNOT_WRITE_DTW_PATH 22
#define CANNOT_WRITE_DBA_AVG 23
#define CANNOT_READ_SEQUENCE_PREFIX_FILE 24
#define CANNOT_COPY_PREFIX_CHOPPED_SEQ 25
#define CANNOT_WRITE_DTW_PATH_MATRIX 26
#define INSUFFICIENT_L1CACHE_FOR_EXPECTED_SEGMENT_SIZE 27 
#endif
